stages:
  feature:
    cmd: python src/models/kitchen_sink/featurize.py data/data data/feature
    deps:
    - src/models/kitchen_sink/featurize.py
    - data/data
    params:
    - featurize.fs_select
    outs:
    - data/feature:
        persist: true
  train:
    cmd: python src/models/kitchen_sink/train.py data/feature/ks_train.csv
    deps:
    - data/feature/ks_train.csv
    params:
    - train.lr
    - train.n_estimators
    - train.objective
    - train.folds
    - train.param_comb
    - train.score
    - train.seed
    outs:
    - parameters.json:
        persist: true