stages:
  feature:
    cmd: python src/models/Kitchen_sink/featurize.py data/data data/feature
    deps:
    - src/models/Kitchen_sink/featurize.py
    - data/data
    params:
    - featurize.fs_select
    outs:
    - data/feature:
        persist: true
  train:
    cmd: python src/models/Kitchen_sink/train.py data/feature/ks_train.csv
    deps:
    - data/feature/cb_train.csv
    params:
    - train.lr
    - train.n_estimators
    - train.objective
    - train.folds
    - train.param_comb
    - train.score
    - train.seed
    outs:
    - parameters.json:
        persist: true
  evaluation:
    cmd: python src/models/kitchen_sink/evaluate.py data/feature data/model/xgb-cl.pkl
    deps:
    - data/feature
    - src/models/kitchen_sink/parameters.json
    outs:
    - data/model/xgb-cl.pkl:
        persist: true
    metrics:
    - score.json:
        cache: false