featurize:
  fs_select : 0
train:
  lr : 0.01
  n_estimators : 1000
  objective : 'multi:softmax'
  folds : 3
  param_comb : 10
  score : 'f1_weighted'
  seed : 443
evaluate:
  lr : 0.02
  n_estimators : 100
  objective : 'multi:softmax'
