featurize:
  fs_select : 0
train:
  lr : 0.02
  n_estimators : 200
  objective : 'multi:softmax'
  folds : 5
  param_comb : 10
  score : 'f1_weighted'
  seed : 443
evaluate:
  lr : 0.02
  n_estimators : 100
  objective : 'multi:softmax'
